// source: encryption.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.encryption.CipherSuite', null, global);
goog.exportSymbol('proto.encryption.EncryptionParameters', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.encryption.EncryptionParameters = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.encryption.EncryptionParameters, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.encryption.EncryptionParameters.displayName = 'proto.encryption.EncryptionParameters';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.encryption.EncryptionParameters.prototype.toObject = function(opt_includeInstance) {
  return proto.encryption.EncryptionParameters.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.encryption.EncryptionParameters} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.encryption.EncryptionParameters.toObject = function(includeInstance, msg) {
  var f, obj = {
    cipherSuite: jspb.Message.getFieldWithDefault(msg, 1, 0),
    blockSize: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.encryption.EncryptionParameters}
 */
proto.encryption.EncryptionParameters.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.encryption.EncryptionParameters;
  return proto.encryption.EncryptionParameters.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.encryption.EncryptionParameters} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.encryption.EncryptionParameters}
 */
proto.encryption.EncryptionParameters.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.encryption.CipherSuite} */ (reader.readEnum());
      msg.setCipherSuite(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setBlockSize(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.encryption.EncryptionParameters.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.encryption.EncryptionParameters.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.encryption.EncryptionParameters} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.encryption.EncryptionParameters.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCipherSuite();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getBlockSize();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
};


/**
 * optional CipherSuite cipher_suite = 1;
 * @return {!proto.encryption.CipherSuite}
 */
proto.encryption.EncryptionParameters.prototype.getCipherSuite = function() {
  return /** @type {!proto.encryption.CipherSuite} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.encryption.CipherSuite} value
 * @return {!proto.encryption.EncryptionParameters} returns this
 */
proto.encryption.EncryptionParameters.prototype.setCipherSuite = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional int64 block_size = 2;
 * @return {number}
 */
proto.encryption.EncryptionParameters.prototype.getBlockSize = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.encryption.EncryptionParameters} returns this
 */
proto.encryption.EncryptionParameters.prototype.setBlockSize = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * @enum {number}
 */
proto.encryption.CipherSuite = {
  ENC_UNSPECIFIED: 0,
  ENC_NULL: 1,
  ENC_AESGCM: 2,
  ENC_SECRETBOX: 3
};

goog.object.extend(exports, proto.encryption);
