// source: scope.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var encryption_access_pb = require('./encryption_access_pb.js');
goog.object.extend(proto, encryption_access_pb);
goog.exportSymbol('proto.scope.Scope', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.scope.Scope = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.scope.Scope, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.scope.Scope.displayName = 'proto.scope.Scope';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.scope.Scope.prototype.toObject = function(opt_includeInstance) {
  return proto.scope.Scope.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.scope.Scope} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.scope.Scope.toObject = function(includeInstance, msg) {
  var f, obj = {
    satelliteAddr: jspb.Message.getFieldWithDefault(msg, 1, ""),
    apiKey: msg.getApiKey_asB64(),
    encryptionAccess: (f = msg.getEncryptionAccess()) && encryption_access_pb.EncryptionAccess.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.scope.Scope}
 */
proto.scope.Scope.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.scope.Scope;
  return proto.scope.Scope.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.scope.Scope} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.scope.Scope}
 */
proto.scope.Scope.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setSatelliteAddr(value);
      break;
    case 2:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setApiKey(value);
      break;
    case 3:
      var value = new encryption_access_pb.EncryptionAccess;
      reader.readMessage(value,encryption_access_pb.EncryptionAccess.deserializeBinaryFromReader);
      msg.setEncryptionAccess(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.scope.Scope.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.scope.Scope.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.scope.Scope} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.scope.Scope.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSatelliteAddr();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getApiKey_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      2,
      f
    );
  }
  f = message.getEncryptionAccess();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      encryption_access_pb.EncryptionAccess.serializeBinaryToWriter
    );
  }
};


/**
 * optional string satellite_addr = 1;
 * @return {string}
 */
proto.scope.Scope.prototype.getSatelliteAddr = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.scope.Scope} returns this
 */
proto.scope.Scope.prototype.setSatelliteAddr = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional bytes api_key = 2;
 * @return {!(string|Uint8Array)}
 */
proto.scope.Scope.prototype.getApiKey = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * optional bytes api_key = 2;
 * This is a type-conversion wrapper around `getApiKey()`
 * @return {string}
 */
proto.scope.Scope.prototype.getApiKey_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getApiKey()));
};


/**
 * optional bytes api_key = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getApiKey()`
 * @return {!Uint8Array}
 */
proto.scope.Scope.prototype.getApiKey_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getApiKey()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.scope.Scope} returns this
 */
proto.scope.Scope.prototype.setApiKey = function(value) {
  return jspb.Message.setProto3BytesField(this, 2, value);
};


/**
 * optional encryption_access.EncryptionAccess encryption_access = 3;
 * @return {?proto.encryption_access.EncryptionAccess}
 */
proto.scope.Scope.prototype.getEncryptionAccess = function() {
  return /** @type{?proto.encryption_access.EncryptionAccess} */ (
    jspb.Message.getWrapperField(this, encryption_access_pb.EncryptionAccess, 3));
};


/**
 * @param {?proto.encryption_access.EncryptionAccess|undefined} value
 * @return {!proto.scope.Scope} returns this
*/
proto.scope.Scope.prototype.setEncryptionAccess = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.scope.Scope} returns this
 */
proto.scope.Scope.prototype.clearEncryptionAccess = function() {
  return this.setEncryptionAccess(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.scope.Scope.prototype.hasEncryptionAccess = function() {
  return jspb.Message.getField(this, 3) != null;
};


goog.object.extend(exports, proto.scope);
