name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - id: storj-release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: storj
          repo: storj
          excludes: prerelease, draft
      - run: echo "🎉 The job was automatically triggered by a ${{ steps.storj-release.outputs.release }} event."
